# Generated by Django 4.1.2 on 2022-10-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_usuario_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
